image: rocker/tidyverse


variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
    - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
    - Rscript -e "renv::restore()"

run:
  script: 
    - Rscript dc_cleaner.R
  artifacts:
    paths:
      - DC_BC.xlsx
